{
  "smtp_server": "smtp.163.com",
  "smtp_port": 465,
  "smtp_user": "lihai0093@163.com",
  "smtp_pass": "PRQKXc2cmcYE25mn",
  "from_email": "lihai0093@163.com",
  "to_emails": [
    "liyongxiang.tech@outlook.com",
    "libluce1@outlook.com",
    ""
  ],
  "subject": "每日天气提醒",
  "body": "<p>早上好，以下是今天的天气信息：</p>",
  "weather": [
    {
      "enabled": true,
      "city": "义乌",
      "latitude": 29.3069,
      "longitude": 120.0753,
      "timezone": "Asia/Shanghai",
      "forecast_days": 3
    },
    {
      "enabled": true,
      "city": "东阳",
      "latitude": 29.2678,
      "longitude": 120.2253,
      "timezone": "Asia/Shanghai",
      "forecast_days": 3
    },
    {
      "enabled": true,
      "city": "杭州",
      "latitude": 30.2741,
      "longitude": 120.1551,
      "timezone": "Asia/Shanghai",
      "forecast_days": 3
    }
  ]
}
